# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: G:/xilin/KUP5P/ddr4 test/doc/kup_ddr.xdc

# IP: ip/ddr4_0/ddr4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr4_0 || ORIG_REF_NAME==ddr4_0} -quiet] -quiet

# IP: g:/xilin/KUP5P/ddr4 test/my_test_ddr4.gen/sources_1/ip/ddr4_0/ip_1/ddr4_0_phy.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr4_0_phy || ORIG_REF_NAME==ddr4_0_phy} -quiet] -quiet

# IP: g:/xilin/KUP5P/ddr4 test/my_test_ddr4.gen/sources_1/ip/ddr4_0/ip_0/ddr4_0_microblaze_mcs.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr4_0_microblaze_mcs || ORIG_REF_NAME==ddr4_0_microblaze_mcs} -quiet] -quiet

# Block Designs: g:/xilin/KUP5P/ddr4 test/my_test_ddr4.gen/sources_1/ip/ddr4_0/bd_0/bd_9054.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9054 || ORIG_REF_NAME==bd_9054} -quiet] -quiet

# IP: g:/xilin/KUP5P/ddr4 test/my_test_ddr4.gen/sources_1/ip/ddr4_0/bd_0/ip/ip_0/bd_9054_microblaze_I_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9054_microblaze_I_0 || ORIG_REF_NAME==bd_9054_microblaze_I_0} -quiet] -quiet

# IP: g:/xilin/KUP5P/ddr4 test/my_test_ddr4.gen/sources_1/ip/ddr4_0/bd_0/ip/ip_1/bd_9054_rst_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9054_rst_0_0 || ORIG_REF_NAME==bd_9054_rst_0_0} -quiet] -quiet

# IP: g:/xilin/KUP5P/ddr4 test/my_test_ddr4.gen/sources_1/ip/ddr4_0/bd_0/ip/ip_2/bd_9054_ilmb_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9054_ilmb_0 || ORIG_REF_NAME==bd_9054_ilmb_0} -quiet] -quiet

# IP: g:/xilin/KUP5P/ddr4 test/my_test_ddr4.gen/sources_1/ip/ddr4_0/bd_0/ip/ip_3/bd_9054_dlmb_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9054_dlmb_0 || ORIG_REF_NAME==bd_9054_dlmb_0} -quiet] -quiet

# IP: g:/xilin/KUP5P/ddr4 test/my_test_ddr4.gen/sources_1/ip/ddr4_0/bd_0/ip/ip_4/bd_9054_dlmb_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9054_dlmb_cntlr_0 || ORIG_REF_NAME==bd_9054_dlmb_cntlr_0} -quiet] -quiet

# IP: g:/xilin/KUP5P/ddr4 test/my_test_ddr4.gen/sources_1/ip/ddr4_0/bd_0/ip/ip_5/bd_9054_ilmb_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9054_ilmb_cntlr_0 || ORIG_REF_NAME==bd_9054_ilmb_cntlr_0} -quiet] -quiet

# IP: g:/xilin/KUP5P/ddr4 test/my_test_ddr4.gen/sources_1/ip/ddr4_0/bd_0/ip/ip_6/bd_9054_lmb_bram_I_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9054_lmb_bram_I_0 || ORIG_REF_NAME==bd_9054_lmb_bram_I_0} -quiet] -quiet

# IP: g:/xilin/KUP5P/ddr4 test/my_test_ddr4.gen/sources_1/ip/ddr4_0/bd_0/ip/ip_7/bd_9054_second_dlmb_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9054_second_dlmb_cntlr_0 || ORIG_REF_NAME==bd_9054_second_dlmb_cntlr_0} -quiet] -quiet

# IP: g:/xilin/KUP5P/ddr4 test/my_test_ddr4.gen/sources_1/ip/ddr4_0/bd_0/ip/ip_8/bd_9054_second_ilmb_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9054_second_ilmb_cntlr_0 || ORIG_REF_NAME==bd_9054_second_ilmb_cntlr_0} -quiet] -quiet

# IP: g:/xilin/KUP5P/ddr4 test/my_test_ddr4.gen/sources_1/ip/ddr4_0/bd_0/ip/ip_9/bd_9054_second_lmb_bram_I_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9054_second_lmb_bram_I_0 || ORIG_REF_NAME==bd_9054_second_lmb_bram_I_0} -quiet] -quiet

# IP: g:/xilin/KUP5P/ddr4 test/my_test_ddr4.gen/sources_1/ip/ddr4_0/bd_0/ip/ip_10/bd_9054_iomodule_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9054_iomodule_0_0 || ORIG_REF_NAME==bd_9054_iomodule_0_0} -quiet] -quiet

# XDC: g:/xilin/KUP5P/ddr4 test/my_test_ddr4.gen/sources_1/ip/ddr4_0/ip_1/par/ddr4_0_phy_ooc.xdc

# XDC: g:/xilin/KUP5P/ddr4 test/my_test_ddr4.gen/sources_1/ip/ddr4_0/bd_0/ip/ip_0/bd_9054_microblaze_I_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_9054_microblaze_I_0 || ORIG_REF_NAME==bd_9054_microblaze_I_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: g:/xilin/KUP5P/ddr4 test/my_test_ddr4.gen/sources_1/ip/ddr4_0/bd_0/ip/ip_0/bd_9054_microblaze_I_0_ooc_debug.xdc

# XDC: g:/xilin/KUP5P/ddr4 test/my_test_ddr4.gen/sources_1/ip/ddr4_0/bd_0/ip/ip_1/bd_9054_rst_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_9054_rst_0_0 || ORIG_REF_NAME==bd_9054_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: g:/xilin/KUP5P/ddr4 test/my_test_ddr4.gen/sources_1/ip/ddr4_0/bd_0/ip/ip_1/bd_9054_rst_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_9054_rst_0_0 || ORIG_REF_NAME==bd_9054_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: g:/xilin/KUP5P/ddr4 test/my_test_ddr4.gen/sources_1/ip/ddr4_0/bd_0/ip/ip_2/bd_9054_ilmb_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_9054_ilmb_0 || ORIG_REF_NAME==bd_9054_ilmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: g:/xilin/KUP5P/ddr4 test/my_test_ddr4.gen/sources_1/ip/ddr4_0/bd_0/ip/ip_3/bd_9054_dlmb_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_9054_dlmb_0 || ORIG_REF_NAME==bd_9054_dlmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: g:/xilin/KUP5P/ddr4 test/my_test_ddr4.gen/sources_1/ip/ddr4_0/bd_0/ip/ip_6/bd_9054_lmb_bram_I_0_ooc.xdc

# XDC: g:/xilin/KUP5P/ddr4 test/my_test_ddr4.gen/sources_1/ip/ddr4_0/bd_0/ip/ip_9/bd_9054_second_lmb_bram_I_0_ooc.xdc

# XDC: g:/xilin/KUP5P/ddr4 test/my_test_ddr4.gen/sources_1/ip/ddr4_0/bd_0/ip/ip_10/bd_9054_iomodule_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_9054_iomodule_0_0 || ORIG_REF_NAME==bd_9054_iomodule_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: g:/xilin/KUP5P/ddr4 test/my_test_ddr4.gen/sources_1/ip/ddr4_0/bd_0/bd_9054_ooc.xdc

# XDC: g:/xilin/KUP5P/ddr4 test/my_test_ddr4.gen/sources_1/ip/ddr4_0/ip_0/ddr4_0_microblaze_mcs_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ddr4_0_microblaze_mcs || ORIG_REF_NAME==ddr4_0_microblaze_mcs} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: g:/xilin/KUP5P/ddr4 test/my_test_ddr4.gen/sources_1/ip/ddr4_0/ip_0/ddr4_0_microblaze_mcs_ooc.xdc

# XDC: g:/xilin/KUP5P/ddr4 test/my_test_ddr4.gen/sources_1/ip/ddr4_0/ddr4_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ddr4_0 || ORIG_REF_NAME==ddr4_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: g:/xilin/KUP5P/ddr4 test/my_test_ddr4.gen/sources_1/ip/ddr4_0/par/ddr4_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ddr4_0 || ORIG_REF_NAME==ddr4_0} -quiet] {/inst } ]/inst ] -quiet] -quiet
