#-----------------------SPI X4 模式----------------------------
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design] 
set_property CONFIG_MODE SPIx4 [current_design] 
set_property BITSTREAM.CONFIG.CONFIGRATE 51.0 [current_design] 
#-----------------------差分系统时钟----------------------------
set_property PACKAGE_PIN T25 [get_ports c0_sys_clk_p]
set_property PACKAGE_PIN U25 [get_ports c0_sys_clk_n]
#------------------------led引脚--------------------------------
set_property PACKAGE_PIN B10 [get_ports led0]
#-----------------------------BG0-------------------------------
set_property PACKAGE_PIN E25 [get_ports {c0_ddr4_bg[0]}]
#-------------------------DDR4 终端电阻使能---------------------
set_property PACKAGE_PIN M24 [get_ports {c0_ddr4_odt[0]}]
#-----------------------------地址线----------------------------
set_property PACKAGE_PIN F22 [get_ports {c0_ddr4_adr[0]}]
set_property PACKAGE_PIN K20 [get_ports {c0_ddr4_adr[1]}]
set_property PACKAGE_PIN C26 [get_ports {c0_ddr4_adr[2]}]
set_property PACKAGE_PIN K18 [get_ports {c0_ddr4_adr[3]}]
set_property PACKAGE_PIN K22 [get_ports {c0_ddr4_adr[4]}]
set_property PACKAGE_PIN L19 [get_ports {c0_ddr4_adr[5]}]
set_property PACKAGE_PIN D23 [get_ports {c0_ddr4_adr[6]}]
set_property PACKAGE_PIN J20 [get_ports {c0_ddr4_adr[7]}]
set_property PACKAGE_PIN C24 [get_ports {c0_ddr4_adr[8]}]
set_property PACKAGE_PIN J19 [get_ports {c0_ddr4_adr[9]}]
set_property PACKAGE_PIN L22 [get_ports {c0_ddr4_adr[10]}]
set_property PACKAGE_PIN B26 [get_ports {c0_ddr4_adr[11]}]
set_property PACKAGE_PIN M20 [get_ports {c0_ddr4_adr[12]}]
set_property PACKAGE_PIN D24 [get_ports {c0_ddr4_adr[13]}]
#------------------------WE  CAS  RAS-------------------------
set_property PACKAGE_PIN F23 [get_ports {c0_ddr4_adr[14]}]
set_property PACKAGE_PIN L18 [get_ports {c0_ddr4_adr[15]}]
set_property PACKAGE_PIN L20 [get_ports {c0_ddr4_adr[16]}]
#-----------------------脉冲选取-----------------------------
set_property PACKAGE_PIN W25 [get_ports {c0_ddr4_dqs_t[1]}]
set_property PACKAGE_PIN W26 [get_ports {c0_ddr4_dqs_c[1]}]
set_property PACKAGE_PIN V21 [get_ports {c0_ddr4_dqs_t[0]}]
set_property PACKAGE_PIN V22 [get_ports {c0_ddr4_dqs_c[0]}]
#--------------------------数据---------------------------
set_property PACKAGE_PIN U22 [get_ports {c0_ddr4_dq[0]}]
set_property PACKAGE_PIN W20 [get_ports {c0_ddr4_dq[1]}]
set_property PACKAGE_PIN U20 [get_ports {c0_ddr4_dq[2]}]
set_property PACKAGE_PIN W19 [get_ports {c0_ddr4_dq[3]}]
set_property PACKAGE_PIN U21 [get_ports {c0_ddr4_dq[4]}]
set_property PACKAGE_PIN T22 [get_ports {c0_ddr4_dq[5]}]
set_property PACKAGE_PIN T23 [get_ports {c0_ddr4_dq[6]}]
set_property PACKAGE_PIN T20 [get_ports {c0_ddr4_dq[7]}]
set_property PACKAGE_PIN AA24 [get_ports {c0_ddr4_dq[8]}]
set_property PACKAGE_PIN Y25 [get_ports {c0_ddr4_dq[9]}]
set_property PACKAGE_PIN V24 [get_ports {c0_ddr4_dq[10]}]
set_property PACKAGE_PIN Y26 [get_ports {c0_ddr4_dq[11]}]
set_property PACKAGE_PIN AA25 [get_ports {c0_ddr4_dq[12]}]
set_property PACKAGE_PIN W24 [get_ports {c0_ddr4_dq[13]}]
set_property PACKAGE_PIN W23 [get_ports {c0_ddr4_dq[14]}]
set_property PACKAGE_PIN V23 [get_ports {c0_ddr4_dq[15]}]
#------------------------CS---------------------------------------
set_property PACKAGE_PIN G22 [get_ports {c0_ddr4_cs_n[0]}]
# ---------------------输出ddr4差分时钟---------------------------
set_property PACKAGE_PIN G24 [get_ports {c0_ddr4_ck_t[0]}]
set_property PACKAGE_PIN G25 [get_ports {c0_ddr4_ck_c[0]}]
#----------------------------CKE----------------------------------
set_property PACKAGE_PIN K23 [get_ports {c0_ddr4_cke[0]}]
#---------------------------RESET---------------------------------
set_property PACKAGE_PIN D26 [get_ports c0_ddr4_reset_n]
#--------------------------ACT-------------------------------------
set_property PACKAGE_PIN M21 [get_ports c0_ddr4_act_n]
#-------------------------BA0  BA1---Bank地址----------------------
set_property PACKAGE_PIN E23 [get_ports {c0_ddr4_ba[0]}]
set_property PACKAGE_PIN H22 [get_ports {c0_ddr4_ba[1]}]
#---------------------   DML   DMU---数据掩码----------------------
set_property PACKAGE_PIN U19 [get_ports {c0_ddr4_dm_dbi_n[0]}]
set_property PACKAGE_PIN Y22 [get_ports {c0_ddr4_dm_dbi_n[1]}]

#--------------------------设置电平标准---------------------------
set_property IOSTANDARD DIFF_SSTL12 [get_ports c0_sys_clk_p]
set_property IOSTANDARD DIFF_SSTL12 [get_ports c0_sys_clk_n]
set_property IOSTANDARD LVCMOS33 [get_ports led0]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dm_dbi_n[0]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dm_dbi_n[1]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[15]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[14]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[13]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[12]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[11]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[10]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[9]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[8]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[7]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[6]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[5]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[4]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[3]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[2]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[1]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[0]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_odt[0]}]
set_property INTERNAL_VREF 0.6 [get_iobanks 66]
set_property INTERNAL_VREF 0.6 [get_iobanks 65]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {c0_ddr4_dqs_t[0]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {c0_ddr4_dqs_c[0]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {c0_ddr4_dqs_t[1]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {c0_ddr4_dqs_c[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports led0]

#--------------------------user io---------------------------
set_property PACKAGE_PIN AF14 [get_ports led1]
set_property PACKAGE_PIN AF15 [get_ports led2]
set_property PACKAGE_PIN AE13 [get_ports led3]
set_property PACKAGE_PIN AF13 [get_ports led4]
set_property PACKAGE_PIN AD15 [get_ports led5]
set_property PACKAGE_PIN AE15 [get_ports led6]
set_property PACKAGE_PIN AD13 [get_ports led7]
set_property PACKAGE_PIN AD14 [get_ports led8]
set_property PACKAGE_PIN AC13 [get_ports led9]
set_property PACKAGE_PIN AC14 [get_ports led10]

set_property PACKAGE_PIN AB16 [get_ports led11]
set_property PACKAGE_PIN Y15 [get_ports led12]
set_property PACKAGE_PIN AA14 [get_ports led13]
set_property PACKAGE_PIN AB14 [get_ports led14]
set_property PACKAGE_PIN Y16 [get_ports led15]
set_property PACKAGE_PIN W14 [get_ports led16]
set_property PACKAGE_PIN W15 [get_ports led17]
set_property PACKAGE_PIN AA13 [get_ports led18]
set_property PACKAGE_PIN W12 [get_ports led19]

set_property PACKAGE_PIN W13 [get_ports led20]
set_property PACKAGE_PIN K10 [get_ports led21]
set_property PACKAGE_PIN K9 [get_ports led22]
set_property PACKAGE_PIN J11 [get_ports led23]
set_property PACKAGE_PIN J10 [get_ports led24]
set_property PACKAGE_PIN J9 [get_ports led25]
set_property PACKAGE_PIN H9 [get_ports led26]
set_property PACKAGE_PIN H11 [get_ports led27]
set_property PACKAGE_PIN G11 [get_ports led28]
set_property PACKAGE_PIN G10 [get_ports led29]

set_property PACKAGE_PIN G9 [get_ports led30]
set_property PACKAGE_PIN F10 [get_ports led31]
set_property PACKAGE_PIN F9 [get_ports led32]
set_property PACKAGE_PIN E11 [get_ports led33]
set_property PACKAGE_PIN E10 [get_ports led34]
set_property PACKAGE_PIN D11 [get_ports led35]
set_property PACKAGE_PIN D10 [get_ports led36]
set_property PACKAGE_PIN D9 [get_ports led37]
set_property PACKAGE_PIN C9 [get_ports led38]
set_property PACKAGE_PIN B9 [get_ports led39]

set_property PACKAGE_PIN A9 [get_ports led41]
set_property PACKAGE_PIN A10 [get_ports led42]
set_property PACKAGE_PIN C11 [get_ports led43]
set_property PACKAGE_PIN B11 [get_ports led44]
set_property PACKAGE_PIN J12 [get_ports led45]
set_property PACKAGE_PIN H12 [get_ports led46]
set_property PACKAGE_PIN J13 [get_ports led47]
set_property PACKAGE_PIN H13 [get_ports led48]
set_property PACKAGE_PIN H14 [get_ports led49]

set_property PACKAGE_PIN G14 [get_ports led50]
set_property PACKAGE_PIN J15 [get_ports led51]
set_property PACKAGE_PIN J14 [get_ports led52]
set_property PACKAGE_PIN G12 [get_ports led53]
set_property PACKAGE_PIN F12 [get_ports led54]
set_property PACKAGE_PIN F14 [get_ports led55]
set_property PACKAGE_PIN F13 [get_ports led56]
set_property PACKAGE_PIN E12 [get_ports led57]
set_property PACKAGE_PIN D14 [get_ports led58]
set_property PACKAGE_PIN D13 [get_ports led59]

set_property PACKAGE_PIN C14 [get_ports led60]
set_property PACKAGE_PIN C13 [get_ports led61]
set_property PACKAGE_PIN C12 [get_ports led62]
set_property PACKAGE_PIN B12 [get_ports led63]
set_property PACKAGE_PIN A13 [get_ports led64]
set_property PACKAGE_PIN A12 [get_ports led65]
set_property PACKAGE_PIN B14 [get_ports led66]
set_property PACKAGE_PIN A14 [get_ports led67]
set_property PACKAGE_PIN AE25 [get_ports led68]
set_property PACKAGE_PIN AE26 [get_ports led69]

set_property PACKAGE_PIN AB25 [get_ports led70]
set_property PACKAGE_PIN AB26 [get_ports led71]
set_property PACKAGE_PIN AF24 [get_ports led72]
set_property PACKAGE_PIN AF25 [get_ports led73]
set_property PACKAGE_PIN AC26 [get_ports led74]
set_property PACKAGE_PIN AD26 [get_ports led75]
set_property PACKAGE_PIN AD24 [get_ports led76]
set_property PACKAGE_PIN AD25 [get_ports led77]
set_property PACKAGE_PIN AB24 [get_ports led78]
set_property PACKAGE_PIN AC24 [get_ports led79]
set_property PACKAGE_PIN AE22 [get_ports led80]

set_property PACKAGE_PIN AF22 [get_ports led81]
set_property PACKAGE_PIN AC22 [get_ports led82]
set_property PACKAGE_PIN AC23 [get_ports led83]
set_property PACKAGE_PIN AD21 [get_ports led84]
set_property PACKAGE_PIN AE21 [get_ports led85]
set_property PACKAGE_PIN AB21 [get_ports led86]
set_property PACKAGE_PIN AC21 [get_ports led87]
set_property PACKAGE_PIN AD20 [get_ports led88]
set_property PACKAGE_PIN AE20 [get_ports led89]
set_property PACKAGE_PIN AC19 [get_ports led90]

set_property PACKAGE_PIN AD19 [get_ports led91]
set_property PACKAGE_PIN AF18 [get_ports led92]
set_property PACKAGE_PIN AF19 [get_ports led93]
set_property PACKAGE_PIN AC18 [get_ports led94]
set_property PACKAGE_PIN AD18 [get_ports led95]
set_property PACKAGE_PIN AE17 [get_ports led96]
set_property PACKAGE_PIN AF17 [get_ports led97]
set_property PACKAGE_PIN AD16 [get_ports led98]
set_property PACKAGE_PIN AE16 [get_ports led99]
set_property PACKAGE_PIN Y20 [get_ports led100]

set_property PACKAGE_PIN Y21 [get_ports led101]
set_property PACKAGE_PIN AA20 [get_ports led102]
set_property PACKAGE_PIN AB20 [get_ports led103]
set_property PACKAGE_PIN AB17 [get_ports led104]
set_property PACKAGE_PIN AC17 [get_ports led105]
set_property PACKAGE_PIN Y17 [get_ports led106]
set_property PACKAGE_PIN AA17 [get_ports led107]
set_property PACKAGE_PIN Y18 [get_ports led108]
set_property PACKAGE_PIN AA18 [get_ports led109]

set_property PACKAGE_PIN U26 [get_ports led110]
set_property PACKAGE_PIN V26 [get_ports led111]
set_property PACKAGE_PIN P25 [get_ports led112]
set_property PACKAGE_PIN P26 [get_ports led113]
set_property PACKAGE_PIN R25 [get_ports led114]
set_property PACKAGE_PIN R26 [get_ports led115]
set_property PACKAGE_PIN P20 [get_ports led116]
set_property PACKAGE_PIN P21 [get_ports led117]
set_property PACKAGE_PIN R20 [get_ports led118]
set_property PACKAGE_PIN R21 [get_ports led119]

set_property PACKAGE_PIN N23 [get_ports led120]
set_property PACKAGE_PIN P23 [get_ports led121]
set_property PACKAGE_PIN N19 [get_ports led122]
set_property PACKAGE_PIN P19 [get_ports led123]
set_property PACKAGE_PIN N21 [get_ports led124]
set_property PACKAGE_PIN N22 [get_ports led125]
set_property PACKAGE_PIN K21 [get_ports led126]
set_property PACKAGE_PIN J21 [get_ports led127]
set_property PACKAGE_PIN M25 [get_ports led128]
set_property PACKAGE_PIN M26 [get_ports led129]

set_property PACKAGE_PIN K25 [get_ports led130]
set_property PACKAGE_PIN K26 [get_ports led131]
set_property PACKAGE_PIN L24 [get_ports led132]
set_property PACKAGE_PIN L25 [get_ports led133]
set_property PACKAGE_PIN J25 [get_ports led134]
set_property PACKAGE_PIN J26 [get_ports led135]
set_property PACKAGE_PIN H26 [get_ports led136]
set_property PACKAGE_PIN G26 [get_ports led137]
set_property PACKAGE_PIN G15 [get_ports led138]
set_property PACKAGE_PIN F15 [get_ports led139]

set_property PACKAGE_PIN H17 [get_ports led140]
set_property PACKAGE_PIN G17 [get_ports led141]
set_property PACKAGE_PIN E15 [get_ports led142]
set_property PACKAGE_PIN D15 [get_ports led143]
set_property PACKAGE_PIN E16 [get_ports led144]
set_property PACKAGE_PIN E17 [get_ports led145]
set_property PACKAGE_PIN H16 [get_ports led146]
set_property PACKAGE_PIN G16 [get_ports led147]
set_property PACKAGE_PIN D16 [get_ports led148]
set_property PACKAGE_PIN C16 [get_ports led149]

set_property PACKAGE_PIN H18 [get_ports led150]
set_property PACKAGE_PIN H19 [get_ports led151]
set_property PACKAGE_PIN G20 [get_ports led152]
set_property PACKAGE_PIN G21 [get_ports led153]
set_property PACKAGE_PIN F20 [get_ports led154]
set_property PACKAGE_PIN E20 [get_ports led155]
set_property PACKAGE_PIN D19 [get_ports led156]
set_property PACKAGE_PIN D20 [get_ports led157]
set_property PACKAGE_PIN C18 [get_ports led158]
set_property PACKAGE_PIN C19 [get_ports led159]


set_property PACKAGE_PIN B19 [get_ports led160]
set_property PACKAGE_PIN B20 [get_ports led161]
set_property PACKAGE_PIN C17 [get_ports led162]
set_property PACKAGE_PIN B17 [get_ports led163]
set_property PACKAGE_PIN A17 [get_ports led164]
set_property PACKAGE_PIN A18 [get_ports led165]
set_property PACKAGE_PIN B15 [get_ports led166]
set_property PACKAGE_PIN A15 [get_ports led167]
set_property PACKAGE_PIN A19 [get_ports led168]
set_property PACKAGE_PIN A20 [get_ports led169]

set_property PACKAGE_PIN A22 [get_ports led170]
set_property PACKAGE_PIN A23 [get_ports led171]
set_property PACKAGE_PIN E21 [get_ports led172]
set_property PACKAGE_PIN D21 [get_ports led173]
set_property PACKAGE_PIN C21 [get_ports led174]
set_property PACKAGE_PIN B21 [get_ports led175]
set_property PACKAGE_PIN A24 [get_ports led176]
set_property PACKAGE_PIN A25 [get_ports led177]
set_property PACKAGE_PIN C22 [get_ports led178]
set_property PACKAGE_PIN B22 [get_ports led179]







set_property IOSTANDARD LVCMOS33 [get_ports led1]
set_property IOSTANDARD LVCMOS33 [get_ports led2]
set_property IOSTANDARD LVCMOS33 [get_ports led3]
set_property IOSTANDARD LVCMOS33 [get_ports led4]
set_property IOSTANDARD LVCMOS33 [get_ports led5]
set_property IOSTANDARD LVCMOS33 [get_ports led6]
set_property IOSTANDARD LVCMOS33 [get_ports led7]
set_property IOSTANDARD LVCMOS33 [get_ports led8]
set_property IOSTANDARD LVCMOS33 [get_ports led9]

set_property IOSTANDARD LVCMOS33 [get_ports led10]
set_property IOSTANDARD LVCMOS33 [get_ports led11]
set_property IOSTANDARD LVCMOS33 [get_ports led12]
set_property IOSTANDARD LVCMOS33 [get_ports led13]
set_property IOSTANDARD LVCMOS33 [get_ports led14]
set_property IOSTANDARD LVCMOS33 [get_ports led15]
set_property IOSTANDARD LVCMOS33 [get_ports led16]
set_property IOSTANDARD LVCMOS33 [get_ports led17]
set_property IOSTANDARD LVCMOS33 [get_ports led18]
set_property IOSTANDARD LVCMOS33 [get_ports led19]

set_property IOSTANDARD LVCMOS33 [get_ports led20]
set_property IOSTANDARD LVCMOS33 [get_ports led21]
set_property IOSTANDARD LVCMOS33 [get_ports led22]
set_property IOSTANDARD LVCMOS33 [get_ports led23]
set_property IOSTANDARD LVCMOS33 [get_ports led24]
set_property IOSTANDARD LVCMOS33 [get_ports led25]
set_property IOSTANDARD LVCMOS33 [get_ports led26]
set_property IOSTANDARD LVCMOS33 [get_ports led27]
set_property IOSTANDARD LVCMOS33 [get_ports led28]
set_property IOSTANDARD LVCMOS33 [get_ports led29]

set_property IOSTANDARD LVCMOS33 [get_ports led30]
set_property IOSTANDARD LVCMOS33 [get_ports led31]
set_property IOSTANDARD LVCMOS33 [get_ports led32]
set_property IOSTANDARD LVCMOS33 [get_ports led33]
set_property IOSTANDARD LVCMOS33 [get_ports led34]
set_property IOSTANDARD LVCMOS33 [get_ports led35]
set_property IOSTANDARD LVCMOS33 [get_ports led36]
set_property IOSTANDARD LVCMOS33 [get_ports led37]
set_property IOSTANDARD LVCMOS33 [get_ports led38]
set_property IOSTANDARD LVCMOS33 [get_ports led39]

set_property IOSTANDARD LVCMOS33 [get_ports led41]
set_property IOSTANDARD LVCMOS33 [get_ports led42]
set_property IOSTANDARD LVCMOS33 [get_ports led43]
set_property IOSTANDARD LVCMOS33 [get_ports led44]
set_property IOSTANDARD LVCMOS33 [get_ports led45]
set_property IOSTANDARD LVCMOS33 [get_ports led46]
set_property IOSTANDARD LVCMOS33 [get_ports led47]
set_property IOSTANDARD LVCMOS33 [get_ports led48]
set_property IOSTANDARD LVCMOS33 [get_ports led49]

set_property IOSTANDARD LVCMOS33 [get_ports led50]
set_property IOSTANDARD LVCMOS33 [get_ports led51]
set_property IOSTANDARD LVCMOS33 [get_ports led52]
set_property IOSTANDARD LVCMOS33 [get_ports led53]
set_property IOSTANDARD LVCMOS33 [get_ports led54]
set_property IOSTANDARD LVCMOS33 [get_ports led55]
set_property IOSTANDARD LVCMOS33 [get_ports led56]
set_property IOSTANDARD LVCMOS33 [get_ports led57]
set_property IOSTANDARD LVCMOS33 [get_ports led58]
set_property IOSTANDARD LVCMOS33 [get_ports led59]

set_property IOSTANDARD LVCMOS33 [get_ports led60]
set_property IOSTANDARD LVCMOS33 [get_ports led61]
set_property IOSTANDARD LVCMOS33 [get_ports led62]
set_property IOSTANDARD LVCMOS33 [get_ports led63]
set_property IOSTANDARD LVCMOS33 [get_ports led64]
set_property IOSTANDARD LVCMOS33 [get_ports led65]
set_property IOSTANDARD LVCMOS33 [get_ports led66]
set_property IOSTANDARD LVCMOS33 [get_ports led67]
set_property IOSTANDARD LVCMOS18 [get_ports led68]
set_property IOSTANDARD LVCMOS18 [get_ports led69]

set_property IOSTANDARD LVCMOS18 [get_ports led70]
set_property IOSTANDARD LVCMOS18 [get_ports led71]
set_property IOSTANDARD LVCMOS18 [get_ports led72]
set_property IOSTANDARD LVCMOS18 [get_ports led73]
set_property IOSTANDARD LVCMOS18 [get_ports led74]
set_property IOSTANDARD LVCMOS18 [get_ports led75]
set_property IOSTANDARD LVCMOS18 [get_ports led76]
set_property IOSTANDARD LVCMOS18 [get_ports led77]
set_property IOSTANDARD LVCMOS18 [get_ports led78]
set_property IOSTANDARD LVCMOS18 [get_ports led79]

set_property IOSTANDARD LVCMOS18 [get_ports led80]
set_property IOSTANDARD LVCMOS18 [get_ports led81]
set_property IOSTANDARD LVCMOS18 [get_ports led82]
set_property IOSTANDARD LVCMOS18 [get_ports led83]
set_property IOSTANDARD LVCMOS18 [get_ports led84]
set_property IOSTANDARD LVCMOS18 [get_ports led85]
set_property IOSTANDARD LVCMOS18 [get_ports led86]
set_property IOSTANDARD LVCMOS18 [get_ports led87]
set_property IOSTANDARD LVCMOS18 [get_ports led88]
set_property IOSTANDARD LVCMOS18 [get_ports led89]

set_property IOSTANDARD LVCMOS18 [get_ports led90]
set_property IOSTANDARD LVCMOS18 [get_ports led91]
set_property IOSTANDARD LVCMOS18 [get_ports led92]
set_property IOSTANDARD LVCMOS18 [get_ports led93]
set_property IOSTANDARD LVCMOS18 [get_ports led94]
set_property IOSTANDARD LVCMOS18 [get_ports led95]
set_property IOSTANDARD LVCMOS18 [get_ports led96]
set_property IOSTANDARD LVCMOS18 [get_ports led97]
set_property IOSTANDARD LVCMOS18 [get_ports led98]
set_property IOSTANDARD LVCMOS18 [get_ports led99]

set_property IOSTANDARD LVCMOS18 [get_ports led100]
set_property IOSTANDARD LVCMOS18 [get_ports led101]
set_property IOSTANDARD LVCMOS18 [get_ports led102]
set_property IOSTANDARD LVCMOS18 [get_ports led103]
set_property IOSTANDARD LVCMOS18 [get_ports led104]
set_property IOSTANDARD LVCMOS18 [get_ports led105]
set_property IOSTANDARD LVCMOS18 [get_ports led106]
set_property IOSTANDARD LVCMOS18 [get_ports led107]
set_property IOSTANDARD LVCMOS18 [get_ports led108]
set_property IOSTANDARD LVCMOS18 [get_ports led109]

set_property IOSTANDARD LVCMOS12 [get_ports led110]
set_property IOSTANDARD LVCMOS12 [get_ports led111]
set_property IOSTANDARD LVCMOS12 [get_ports led112]
set_property IOSTANDARD LVCMOS12 [get_ports led113]
set_property IOSTANDARD LVCMOS12 [get_ports led114]
set_property IOSTANDARD LVCMOS12 [get_ports led115]
set_property IOSTANDARD LVCMOS12 [get_ports led116]
set_property IOSTANDARD LVCMOS12 [get_ports led117]
set_property IOSTANDARD LVCMOS12 [get_ports led118]
set_property IOSTANDARD LVCMOS12 [get_ports led119]

set_property IOSTANDARD LVCMOS12 [get_ports led120]
set_property IOSTANDARD LVCMOS12 [get_ports led121]
set_property IOSTANDARD LVCMOS12 [get_ports led122]
set_property IOSTANDARD LVCMOS12 [get_ports led123]
set_property IOSTANDARD LVCMOS12 [get_ports led124]
set_property IOSTANDARD LVCMOS12 [get_ports led125]
set_property IOSTANDARD LVCMOS12 [get_ports led126]
set_property IOSTANDARD LVCMOS12 [get_ports led127]
set_property IOSTANDARD LVCMOS12 [get_ports led128]
set_property IOSTANDARD LVCMOS12 [get_ports led129]

set_property IOSTANDARD LVCMOS12 [get_ports led130]
set_property IOSTANDARD LVCMOS12 [get_ports led131]
set_property IOSTANDARD LVCMOS12 [get_ports led132]
set_property IOSTANDARD LVCMOS12 [get_ports led133]
set_property IOSTANDARD LVCMOS12 [get_ports led134]
set_property IOSTANDARD LVCMOS12 [get_ports led135]
set_property IOSTANDARD LVCMOS12 [get_ports led136]
set_property IOSTANDARD LVCMOS12 [get_ports led137]
set_property IOSTANDARD LVCMOS18 [get_ports led138]
set_property IOSTANDARD LVCMOS18 [get_ports led139]

set_property IOSTANDARD LVCMOS18 [get_ports led140]
set_property IOSTANDARD LVCMOS18 [get_ports led141]
set_property IOSTANDARD LVCMOS18 [get_ports led142]
set_property IOSTANDARD LVCMOS18 [get_ports led143]
set_property IOSTANDARD LVCMOS18 [get_ports led144]
set_property IOSTANDARD LVCMOS18 [get_ports led145]
set_property IOSTANDARD LVCMOS18 [get_ports led146]
set_property IOSTANDARD LVCMOS18 [get_ports led147]
set_property IOSTANDARD LVCMOS18 [get_ports led148]
set_property IOSTANDARD LVCMOS18 [get_ports led149]

set_property IOSTANDARD LVCMOS18 [get_ports led150]
set_property IOSTANDARD LVCMOS18 [get_ports led151]
set_property IOSTANDARD LVCMOS18 [get_ports led152]
set_property IOSTANDARD LVCMOS18 [get_ports led153]
set_property IOSTANDARD LVCMOS18 [get_ports led154]
set_property IOSTANDARD LVCMOS18 [get_ports led155]
set_property IOSTANDARD LVCMOS18 [get_ports led156]
set_property IOSTANDARD LVCMOS18 [get_ports led157]
set_property IOSTANDARD LVCMOS18 [get_ports led158]
set_property IOSTANDARD LVCMOS18 [get_ports led159]

set_property IOSTANDARD LVCMOS18 [get_ports led160]
set_property IOSTANDARD LVCMOS18 [get_ports led161]
set_property IOSTANDARD LVCMOS18 [get_ports led162]
set_property IOSTANDARD LVCMOS18 [get_ports led163]
set_property IOSTANDARD LVCMOS18 [get_ports led164]
set_property IOSTANDARD LVCMOS18 [get_ports led165]
set_property IOSTANDARD LVCMOS18 [get_ports led166]
set_property IOSTANDARD LVCMOS18 [get_ports led167]
set_property IOSTANDARD LVCMOS18 [get_ports led168]
set_property IOSTANDARD LVCMOS18 [get_ports led169]

set_property IOSTANDARD LVCMOS18 [get_ports led170]
set_property IOSTANDARD LVCMOS18 [get_ports led171]
set_property IOSTANDARD LVCMOS18 [get_ports led172]
set_property IOSTANDARD LVCMOS18 [get_ports led173]
set_property IOSTANDARD LVCMOS18 [get_ports led174]
set_property IOSTANDARD LVCMOS18 [get_ports led175]
set_property IOSTANDARD LVCMOS18 [get_ports led176]
set_property IOSTANDARD LVCMOS18 [get_ports led177]
set_property IOSTANDARD LVCMOS18 [get_ports led178]
set_property IOSTANDARD LVCMOS18 [get_ports led179]


set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
